### ISSUE TITLE
Random TODO

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/r-bloggers#1]
- [ ] [How to Setup ProjectSend File sharing Tool on CentOS 7](https://linoxide.com/tools/setup-projectsend-file-sharing-centos-7/)
- [ ] [Using Intel® MKL with R](https://software.intel.com/en-us/articles/using-intel-mkl-with-r)
- [ ] [The Unix Workbench](https://seankross.com/the-unix-workbench/)
- [ ] [The R in Spark: Learn Apache Spark using R](https://therinspark.com/)
- [ ] [Introduction to Data Technologies](https://www.stat.auckland.ac.nz/~paul/ItDT/) https://www.crcpress.com/p/book/9781420065176
- [ ] [ShinyProxy is a novel, open source platform to deploy Shiny apps for the enterprise
or larger organizations](https://github.com/openanalytics/shinyproxy-config-examples)
- [ ] [Docker Swarm](https://docs.docker.com/engine/swarm/)
- [ ] [Kubernetes (k8s) is an open-source system for automating deployment, scaling, and management of containerized applications](https://kubernetes.io/)

## NLP

- [ ] [A workshop on analyzing topic modeling (LDA, CTM, STM) using R](https://github.com/wesslen/Topic-Modeling-Workshop-with-R)
- [ ] [CRAN Task View: Natural Language Processing](https://CRAN.R-project.org/view=NaturalLanguageProcessing)
