### ISSUE TITLE
introduction to docker

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/r-bloggers#17]
**TODO**
---

过时主站文章处理方式

- 一篇主站文章的生命周期，对于统计软件介绍类的文章，特别是功能性介绍，涉及复杂依赖，众多 R 包
- 撤下过时的文章，比如作者不愿意更新了，若有接盘侠重写文章内容，应该更新作者名称，仿照过期 R 包处理方式
- 从深度上讲，软件介绍类的文章都相对简单易写，所以可重复性，可维护性是重点，这也是保持这类文章生命力的关键
- 我们甚至应该要求这类文章的作者提供可重复的运行环境如虚拟机镜像， docker 镜像/ dockerfile 
- 我们是否应该曝光这类文章，鼓励社区其他人，若有时间欢迎更新

HIVE 与 R 更新过时文章 https://cosx.org/2013/07/r-nosql-hive
---

- [ ] 各个组件依赖关系图 https://github.com/ruoyu-chen/hadoop-docker 基于Docker构建的Hadoop开发测试环境，包含Hadoop，Hive，HBase，Spark
- [ ] 靠谱的 Hive 集群 https://github.com/big-data-europe/docker-hive **推荐**
- [ ] HiveODBC 驱动 https://cwiki.apache.org/confluence/display/Hive/HiveODBC
- [ ] Apache Hive https://db.rstudio.com/databases/hive/
- [ ] spark and hive backends for dplyr https://github.com/rzilla/dplyr.spark.hive
- [ ] RHive is an R extension facilitating distributed computing via Apache Hive https://github.com/nexr/RHive
- [ ] 利用 JDBC 驱动连接 R 和 Hive https://www.bjt.name/2016/11/19/jdbc-hive-r.html **推荐**
- [ ] RHive 不再维护了 https://cran.r-project.org/src/contrib/Archive/RHive/
- [ ] R 利剑 NoSQL 系列文章 之 Hive https://cosx.org/2013/07/r-nosql-hive
- [ ] 使用 Microsoft Hive ODBC 驱动程序将 Excel 连接到 Azure HDInsight 中的 Apache Hadoop https://docs.microsoft.com/zh-cn/azure/hdinsight/hadoop/apache-hadoop-connect-excel-hive-odbc-driver Windows 环境下连接 hive

- ODBC Hive Connection makes Rstudio crash // Connection pane issue?
https://stackoverflow.com/questions/57188891

**Comment by XiangyunHuang** [comment]
已完成，见 <https://www.xiangyunhuang.com.cn/post/2017/05/19/rocker-docker/>
